import numpy as np
import torch
from transformers import AutoModelForQuestionAnswering, AutoTokenizer

from clickbait_spoiling.models.model_factory import resolve_checkpoint


def build_qa_model(model_name: str):
    """Returns (model, tokenizer) = (AutoModelForQuestionAnswering, AutoTokenizer)
    for Task 2 extractive QA.
    """
    checkpoint = resolve_checkpoint(model_name)
    tokenizer = AutoTokenizer.from_pretrained(checkpoint)
    model = AutoModelForQuestionAnswering.from_pretrained(checkpoint)
    return model, tokenizer


class SpoilerSpanExtractor:
    """Thin inference wrapper around an AutoModelForQuestionAnswering model."""

    def __init__(self, model, tokenizer, device: str = "cpu"):
        self.model = model
        self.tokenizer = tokenizer
        self.device = torch.device(device)
        self.model.to(self.device)
        self.model.eval()

    def predict_logits(self, features: dict) -> tuple[np.ndarray, np.ndarray]:
        """Given tokenized question+context features, returns (start_logits, end_logits) as numpy arrays.
        Handles missing token_type_ids safely.
        """
        input_ids = torch.tensor(features["input_ids"]).unsqueeze(0).to(self.device)
        attention_mask = (
            torch.tensor(features["attention_mask"]).unsqueeze(0).to(self.device)
        )

        # Check if token_type_ids are generated by the tokenizer (e.g. DeBERTa-v3 does not always use them)
        kwargs = {}
        if "token_type_ids" in features:
            kwargs["token_type_ids"] = (
                torch.tensor(features["token_type_ids"]).unsqueeze(0).to(self.device)
            )

        with torch.no_grad():
            outputs = self.model(
                input_ids=input_ids, attention_mask=attention_mask, **kwargs
            )

        start_logits = outputs.start_logits[0].cpu().numpy()
        end_logits = outputs.end_logits[0].cpu().numpy()
        return start_logits, end_logits
